run:
  timeout: 5m
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test.go"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - unused
    - gofmt
    - gocritic
    - revive

issues:
  exclude-use-default: false

linters-settings:
  gofmt:
    simplify: true

  revive:
    severity: warning
    rules:
      - name: var-naming
        arguments: ["camelCase"]
      - name: indent-error-flow
      - name: error-return